### ISSUE TITLE
ssh agent support

### ISSUE THREAD

**Issue by xgdgsc** [flathub/org.filezillaproject.Filezilla#17]
Is it possible to support ssh agents like https://github.com/flatpak/flatpak/issues/1438 ? It would be useful for using key files for server access.

**Comment by nedrichards** [comment]
Can you test it? The instructions on that issue should give you a good idea about the CLI bits to twiddle. If it works I'd absolutely take a patch.

**Comment by xgdgsc** [comment]
I haven' t learned how to develop flatpak packages and I may not have time to do it in one month. If after that I have time, I would test it.

**Comment by nedrichards** [comment]
Testing manually you would type:
> flatpak run --socket=ssh-auth org.filezillaproject.Filezilla

More generally this requires at least [flatpak 0.10.3](https://github.com/flatpak/flatpak/releases/tag/0.10.3) (releases before then fail when they see unknown permissions). We only have flathub version stats from Flatpak 0.11.3 onwards, and that or newer is currently at 60% of usage. I'd love to see that get higher before we turn this on by default. (we believe the main 'offender' is CentOS/RHEL which are on 0.8.8 fwiw.)

**Comment by nedrichards** [comment]
Fixed in https://github.com/flathub/org.filezillaproject.Filezilla/commit/fc131c33227d05e06c78ba4c3598e6b415a8cdeb

Works fine in my local testing.
