### ISSUE TITLE
Update the screenshot

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/org.filezillaproject.Filezilla#19]
The screenshot looks so old...

**Comment by TingPing** [comment]
PR welcomed.

**Comment by bilelmoussaoui** [comment]
Something like this will do the job? 
![screenshot from 2018-09-22 18-12-11](https://user-images.githubusercontent.com/7660997/45919279-19f8b600-be93-11e8-8bef-3abbf2b35bbe.png)

**Comment by TingPing** [comment]
Should be 16:9

**Comment by bilelmoussaoui** [comment]
Fixed on master
