### ISSUE TITLE
No window decoration under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.filezillaproject.Filezilla#20]
Hi
I use Arch Linux, Filezilla installed from flathub has no window decoration under KDE Plasma Wayland session. The same problem does not occur with Filezilla 3.37.1 installed from Arch repos.

**Comment by TingPing** [comment]
Seems like the same version of wxwidgets at least.

**Comment by glaubersm** [comment]
Fixed with filezilla 3.38.1 on the same system. \o/
