### ISSUE TITLE
2019-03-18 - FileZilla Client 3.41.2 released

### ISSUE THREAD

**Issue by ovari** [flathub/org.filezillaproject.Filezilla#32]
Fixed vulnerabilities:
- Backport a security fix from PuTTY 0.71 affecting SFTP connections: Fix an integer overflow in the RSA key exchange preceeding host key verification

https://filezilla-project.org/

**Comment by nedrichards** [comment]
Resolved by https://github.com/flathub/org.filezillaproject.Filezilla/commit/d74278f2b7618007da4cb52f854376a6f4f976ad patches welcome!

**Comment by ovari** [comment]
Thank you
