### ISSUE TITLE
New version - 3.42.0

### ISSUE THREAD

**Issue by pizzadude** [flathub/org.filezillaproject.Filezilla#33]
3.42.0 (2019-05-06)

- Fixed a potential crash if the first-launch welcome dialog is shown at an inopportune moment
- Fixed display of subject and issuer details in the certificate verification dialogs with some certificates
- Official binaries are now built againt GnuTLS 3.6.7, minimum required GnuTLS version to build FileZilla is now 3.5.7

3.42.0-rc1 (2019-04-26)

- Switching from using a master password to not saving passwords at all no longer requires entering the master password
- *nix: Fixed support for internationalized domain names on systems having AI_IDN when using SFTP
- Fixed an assertion after importing a manipulated queue file
- When importing sites, any imported passwords are now immediately protected/deleted depending on the password protection settings
- The ability to import Sitem Manager entries from antique FileZilla 2, last updated over a dozen years ago, has been removed

3.42.0-beta1 (2019-04-21)

- Building and running FileZilla now depends on libfilezilla >= 0.16.0 (https://lib.filezilla-project.org/)
- Limit the maximum length of site, bookmark and filter names to prevent display issues and crashes due to some operating systems badly handling long texts
- When displaying message boxes, insert zero-width spaces into long unbroken words to prevent display issues and crashes due to some operating systems badly handling long texts
- Fix crash in the external IP address resolver
- Fix some assertions if a server sends bad file sizes
- Large refactoring of the socket code
- The thread pool from libfilezilla is now used for all worker threads

**Comment by nedrichards** [comment]
Resolved in https://github.com/flathub/org.filezillaproject.Filezilla/commit/1b7ee78ab238df1a0cc042d29b275db232f7aaf7 although as ever, patches welcome!
