### ISSUE TITLE
Using GNOME Software didn't provide the french version : I had to install within a Terminal org.filezillaproject.Filezilla.Locale

### ISSUE THREAD

**Issue by antistress** [flathub/org.filezillaproject.Filezilla#35]
Hi,
I'm using Debian 64 bits Sid with GNOME X11 in french (flatpak version is 1.2.4-1 and gnome-software version is 3.30.6-5)
I've installed different applications from flathub using GNOME Software : some of them were translated in french, some of them don't.
For Filezilla I had to open a Terminal and to manually install org.filezillaproject.Filezilla.Locale
Then Filezilla was translated.

Thanks.

**Comment by antistress** [comment]
I've reported the bug against gnome-software here https://gitlab.gnome.org/GNOME/gnome-software/issues/705

**Comment by bilelmoussaoui** [comment]
This is an upstream issue.
