### ISSUE TITLE
Problem encountered at startup

### ISSUE THREAD

**Issue by scafroglia93** [flathub/org.filezillaproject.Filezilla#4]
![schermata del 2018-01-20 13-09-13](https://user-images.githubusercontent.com/8227101/35183285-934cd732-fde3-11e7-921e-144289cdc507.png)

**Comment by glaubersm** [comment]
I can confirm this bug on Arch Linux.

**Comment by nakednorman** [comment]
Also get this on Mint 18.3

**Comment by nakednorman** [comment]
Looks like a known error in "wxWidgets", see https://trac.filezilla-project.org/ticket/11436?format=rss

**Comment by nedrichards** [comment]
Thanks @nakednorman sadly it looks like a 3.0.4 release is still a little way away so I've cherry picked that commit. Running a test build now.

**Comment by nakednorman** [comment]
@nedrichards 
Just tried it - works perfectly!
Many thanks.
