### ISSUE TITLE
The new update seem unavailable

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.filezillaproject.Filezilla#47]
The newest update doesn't seem to be published on Flathub. The last one I can install is 3.47.1.

**Comment by antistress** [comment]
Also org.filezillaproject.Filezilla doesn't stop warning me that a new version is available at each startup (3.47.2.1 as of today)
Shall I fill a separate bug ?

**Comment by bilelmoussaoui** [comment]
I have started a new build here https://flathub.org/builds/#/builders/32/builds/18179

**Comment by bilelmoussaoui** [comment]
Published https://flathub.org/apps/details/org.filezillaproject.Filezilla
