### ISSUE TITLE
Lacks MimeType handlers for ftp:// etc. URI schemes

### ISSUE THREAD

**Issue by wjt** [flathub/org.filezillaproject.Filezilla#69]
Apps can declare what URI schemes they support in their `.desktop` file as follows:

```
MimeType=x-scheme-handler/ftp;x-scheme-handler/sftp;x-scheme-handler/ftps;
```

Filezilla declares no such thing, so is not registered to handle `ftp://` links in other apps. But if launched with one it works fine.

(I am aware that this is an upstream issue; but I am not in the mood to sign up for Trac today.)

**Comment by wjt** [comment]
Here's the 6-year-old upstream issue with patch: https://trac.filezilla-project.org/ticket/10724#no1

**Comment by wjt** [comment]
`/usr/share/applications/filezilla.desktop` indicates that you are not using the Flatpak version of Filezilla.

**Comment by wjt** [comment]
(Notice that the upstream patch was never merged upstream; it was applied to this Flatpak.)

**Comment by sh3bang** [comment]
@wjt i have removed FileZilla and installed it now as flatpack. Same behavior: FileZilla open, but nothing else happens

```
$ flatpak info org.filezillaproject.Filezilla

FileZilla - Fast and reliable FTP client

         Kennung: org.filezillaproject.Filezilla
             Ref: app/org.filezillaproject.Filezilla/x86_64/stable
     Architektur: x86_64
           Zweig: stable
         Version: 3.66.1
          Lizenz: GPL-2.0-or-later
        Ursprung: flathub
        Sammlung: org.flathub.Stable
    Installation: system
     Installiert: 34,5 MB
Laufzeitumgebung: org.freedesktop.Platform/x86_64/23.08
             Sdk: org.freedesktop.Sdk/x86_64/23.08

          Commit: 98f705245fde8108fce14f2206aeb268b74490060a1a3a808bb96de7a3bbc9fd
          Parent: 5afaa7f8d0fcdc249c5cc0c4d4560815e9a57b2bc27381576d8dafad622d3f70
         Betreff: update to 3.66.1 (#96) (6207b767)
           Datum: 2023-11-05 08:32:33 +0000
```

**Comment by wjt** [comment]
I see the problem.

**Comment by wjt** [comment]
Fixed in https://github.com/flathub/org.filezillaproject.Filezilla/pull/99 (awaiting review)

**Comment by razzeee** [comment]
Should hopefully be better with the next release
