### ISSUE TITLE
Crash on arm

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.filezillaproject.Filezilla#8]
ARM: crashes upon launch: "invalid source position for vertical gradient"

**Comment by nedrichards** [comment]
Quite likely to be a generic wxwidgets bug, yes.

**Comment by nedrichards** [comment]
Need to retest with 3.32 since that upgrades to wx 3.3.4 which supposedly has a number of wxgtk fixes.

**Comment by ramcq** [comment]
Works here with 3.45.1 on my Endless Mini (AML S805, Mali 450, kernel 3.10).
