### ISSUE TITLE
version 3.60.1 for armv7l missing?

### ISSUE THREAD

**Issue by glodomorrapl** [flathub/org.filezillaproject.Filezilla#81]
i wanted to use the latest version of filezilla on my raspberry pi running raspbian, so i went along with the recommendation to install it from flathub. but even though the flathub page says version 3.60.1, only version 3.50.0 gets installed on my system. why? is filezilla discontinued for this arch?

**Comment by nedrichards** [comment]
Yep, 32bit ARM support was removed from our upstream runtime so no further updates can be published. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1105 and https://discourse.flathub.org/t/revisiting-arm-32-bits-support-answer-no/924 has a bit more information. 64bit Raspbian remains supported.

This information is also available on the flatpak.org install page for raspbian: https://flatpak.org/setup/Raspberry%20Pi%20OS

> Important note: As of March 2021, Raspberry Pi computers still ship with the 32-bit version of Raspberry Pi OS. However Flathub started phasing out support for that architecture. If you consider Flathub as an important source of applications, it is recommended to use Raspberry Pi OS 64-bit as newer applications are more likely to be available for that platform.
