### ISSUE TITLE
Summary is too long

### ISSUE THREAD

**Issue by razzeee** [flathub/org.filezillaproject.Filezilla#93]
Blogs like https://blogs.gnome.org/tbernard/2021/09/07/ready-for-software-41/ suggest that summarise should be shorter, so it would be nice to come up with a shorter one for this app.

**Comment by nedrichards** [comment]
Shortened in https://github.com/flathub/org.filezillaproject.Filezilla/pull/94/commits/9ac2fb9daa23ba8da9bf186171f4d4292e68752f
